### ISSUE TITLE
share this to all of your friends for good luck!

### ISSUE THREAD

**Issue by dndrheadof** [jppteam/the-sus#2]
Loud 🔊 dubstep intro 🕳 with rotating 🔄 3D 🤩‼ text 📲 Hey 👋, whaddup guys 👨, it's your 👉 boi 🗳✔, <insert 🍌👋 edgy 🍆 name 🏷 here> here, and today 📅 I'm 😮 gonna show 📺 you 👆 this easy-to-do awesome 👍 little 👌 glitch for easy 🐳🏴󠁧󠁢󠁷󠁬󠁳󠁿 unlimited 💪 money 🤑 solo 💯. Before 😂 showing 📺 you 👆 this glitch I'd 😣 just like 👍 to take 👫 a minute ⏰ and talk 🗣 about what I ☝ want ⚠ to do with the channel 🌍📺 in the future 📡. I 👁 know 🤔 you 👆 guys 👨 have been liking 👍 my latest 🥳 videos 🎥 a lot 💯 but 🍑 I'd 😗 love 😍 to see 👀 some comments 🍆 on how to improve 💸 my videos 📹 in the future 📡. And guys 👦, last ♿ video 🎥 had the amazing 🤩💙💛 amount 💱 of likes 👍 of 1.000 ⬆, so let's 👏 see 👀 if we can get more than that, maybe 🤔 2.000!! So be sure 💯 to smash 😩 that likebutton and if you 👉🏻 haven't already 😞, be sure 💯 to subscribe 🥵. If we make 🛠 it to 2.000 likes 👍, I ☝ might 🤔 do a sharkcard giveaway 🎉 next 👉 week 🌖🌑, so you 👉🏻 don't wanna 😱 miss 😞 it! So don't forget to both subscribe 📥✅ and hit 👊 that bell 🛎🔕🔔 next ♊ to the subscribe 📷 button 💯, and then apply 😤🤔 for getting all 😳 my notifications 👀, so you 👉🏻 can be sure 💯 to see 👀 my next ♊ videos 📼. I 👁 make 🛠 a lot 💯 of daily 📆 GTA content 🗞 that I'm 😮 sure 💯 will fit 🙌 most of you 👆 guys 👦 out there. They range 👻🤛🟨 from glitches, to highlights and all 🏳️‍🌈 kind 🖐🏾 of neat 😫😡 stuff 😜. But 🍑 if you're not only into GTA, that's ↗ ok 👌🏻, as I 👁 have a cool 😎 G2A coupon 🎫 code 🚱: "G1TGUD", which gives you 👉🏻 a whooping 3 🔡🔀⏬% off your 👉 purchases 👷‍♀️. And I'm 👈 not only giving 👉 you 👆 that coupon 🎫 code 🚱 so I 👁 can build 🏢 up ⬆ reward 🎁🅱 money 🤑 from a shady 🌑 company 🏢👁, but 🍑 also 😝💝 give 🎁 something back ⬅ to you 👆 guys 👨 for helping 💁 me out a ton 💰 on this channel 🌍📺. I 👁 have got 💪 to say 💬 that it's all 🏳️‍🌈 possible 🙅🏻‍♀️👨‍👨‍👦 because of you 👆 guys 👨. I 👁 can't 🙅‍♀️🙅‍♂️ say 🗣 this enough 💦, thank 🙏 you 👆 guys 👨🏾 so much 😩😂🙀 for your 👉 support ✔. You 👆 really 💯 mean 😏 the world 🌍🌎🌏 to me. But 😳 I ☝ think 💭 I'm 👈 just rambling too much 😩😂🙀 here, so I ☝ think 🤔 we'll 🤔 move 📦 on to the actual glitch. Ok 👌 so guys 👦 this glitch was found 🔎 by my friend 🐶 xXx_B00tYm4$ter_2001_xXxSwagzX and he 👨 just started 🆕 his 👋 youtube 👨🏾‍💻 channel 🌍📺 and could really 💯 use some of your 👉 guys' 👦 help 🆘! I'll 🤒 leave 🍑🍆💦 his 👋 channel 🌍📺 in the description 🗣 down ⬇ below 👇🏻 so be sure 💯 to check ✔ him 👴 out after 2️⃣ this video 🎥 and give 🎁 his 👋 videos 📼 a ton 🏋️‍♂️ of likes 👍 and subscribe 📥✅ to him 👴 so he 👨 can find 🔎 more of this awesome 👍 glitches, just for you 👆 guys 👦!! Ok 👌🏻 so for this glitch you'll need a garage. Get your 👉 car 🚗 to the garage, kill 🔪 yourself and there you 👉🏻 have it! Awesome 👍 duplication glitch and see 👁 you 👆 guys 👦 in the next 👉 video 📼! Loud 🔊 dubstep outro with rotating 🔄 3D 😎 text 📲 and annotations 😏 to other videos 📹 with clickbait 😲🤤 thumbnails

**Comment by tangenx** [comment]
Олег зажигает в клубе "Фуррии" с треком "ПАФОСНАЯ ГЕРОИЧЕСКАЯ МУЗЫКА – ПОД КОТОРУЮ УДОБНО БЫТЬ КИРОЙ"! Заходи ко мне в клуб прямо сейчас по ссылке ▶

**Comment by m4l3vich** [comment]
when maki osi bild😡

**Comment by dndrheadof** [comment]
Stop saying the word cum so much are you fucking retarded? What's so funny about semen? AHAHAHAHA CUM COOM CAM CAM HAHAHA LOOK AT ME. SEXSEXSEXX AAAHHAAHAH!!!!!!SHUT THE FUCK UP MAKE IT STOP. Me (M18) and my gf (F19) were doing the good sexy sex when I decided to browse Reddit and then I see it: CUM!!!!!!! WHYYYYYYY??? WHY ARE YOU DOING THIS????? THATS SO FUCKING DISGUSTING AND IMMATURE AND MY GF LEFT ME AFTER SHE READ THAT! THATS SO FUNNY FOR YOU ISN'T IT???? ISNT IT WHAT YOU WANTED??? NOONE RUINS MY SEX SEXY SEX SEX WITH MY FEMALE COMPANION.

**Comment by dndrheadof** [comment]
Sincerely, FUCK YOU

**Comment by dndrheadof** [comment]
![image](https://user-images.githubusercontent.com/35174807/166274256-8d70e4a0-c051-4a00-ae1c-ecf772b9eb2d.png)

**Comment by dndrheadof** [comment]
⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠁⠄⠄⠄⠄⠄⠄⠄⠄⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡟⠁⠄⠄⠄⠄⣠⣤⣴⣶⣶⣶⣶⣤⡀⠈⠙⢿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡟⠄⠄⠄⠄⠄⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠄⠈⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⠁⠄⠄⠄⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄⢺⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡄⠄⠄⠄⠙⠻⠿⣿⣿⣿⣿⠿⠿⠛⠛⠻⣿⡄⠄⣾⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡇⠄⠄⠁ 👁 ⠄⢹⣿⡗⠄ 👁 ⢄⡀⣾⢀⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡇⠘⠄⠄⠄⢀⡀⠄⣿⣿⣷⣤⣤⣾⣿⣿⣿⣧⢸⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡇⠄⣰⣿⡿⠟⠃⠄⣿⣿⣿⣿⣿⡛⠿⢿⣿⣷⣾⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡄⠈⠁⠄⠄⠄⠄⠻⠿⢛⣿⣿⠿⠂⠄⢹⢹⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⡐⠐⠄⠄⣠⣀⣀⣚⣯⣵⣶⠆⣰⠄⠞⣾⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣷⡄⠄⠄⠈⠛⠿⠿⠿⣻⡏⢠⣿⣎⣾⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡿⠟⠛⠄⠄⠄⠄⠙⣛⣿⣿⣵⣿⡿⢹⡟⣿⣿⣿⣿⣿⣿⣿
⣿⠿⠿⠋⠉⠄⠄⠄⠄⠄⠄⠄⣀⣠⣾⣿⣿⣿⡟⠁⠹⡇⣸⣿⣿⣿⣿⣿⣿
⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠙⠿⠿⠛⠋⠄⣸⣦⣠⣿⣿⣿⣿⣿⣿⣿

**Comment by m4l3vich** [comment]
![image](https://user-images.githubusercontent.com/23311163/166292506-67f13b4a-1d8e-4c9d-bd40-cb6cf07b4cee.png)

**Comment by tailsjs** [comment]
———————————No bitches?———————————
⠀⣞⢽⢪⢣⢣⢣⢫⡺⡵⣝⡮⣗⢷⢽⢽⢽⣮⡷⡽⣜⣜⢮⢺⣜⢷⢽⢝⡽⣝
⠸⡸⠜⠕⠕⠁⢁⢇⢏⢽⢺⣪⡳⡝⣎⣏⢯⢞⡿⣟⣷⣳⢯⡷⣽⢽⢯⣳⣫⠇
⠀⠀⢀⢀⢄⢬⢪⡪⡎⣆⡈⠚⠜⠕⠇⠗⠝⢕⢯⢫⣞⣯⣿⣻⡽⣏⢗⣗⠏⠀
⠀⠪⡪⡪⣪⢪⢺⢸⢢⢓⢆⢤⢀⠀⠀⠀⠀⠈⢊⢞⡾⣿⡯⣏⢮⠷⠁⠀⠀
⠀⠀⠀⠈⠊⠆⡃⠕⢕⢇⢇⢇⢇⢇⢏⢎⢎⢆⢄⠀⢑⣽⣿⢝⠲⠉⠀⠀⠀⠀
⠀⠀⠀⠀⠀⡿⠂⠠⠀⡇⢇⠕⢈⣀⠀⠁⠡⠣⡣⡫⣂⣿⠯⢪⠰⠂⠀⠀⠀⠀
⠀⠀⠀⠀⡦⡙⡂⢀⢤⢣⠣⡈⣾⡃⠠⠄⠀⡄⢱⣌⣶⢏⢊⠂⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢝⡲⣜⡮⡏⢎⢌⢂⠙⠢⠐⢀⢘⢵⣽⣿⡿⠁⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠨⣺⡺⡕⡕⡱⡑⡆⡕⡅⡕⡜⡼⢽⡻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣼⣳⣫⣾⣵⣗⡵⡱⡡⢣⢑⢕⢜⢕⡝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣴⣿⣾⣿⣿⣿⡿⡽⡑⢌⠪⡢⡣⣣⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡟⡾⣿⢿⢿⢵⣽⣾⣼⣘⢸⢸⣞⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠁⠇⠡⠩⡫⢿⣝⡻⡮⣒⢽⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
—————————————————————————————
